;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-backward-char
	evil-beginning-of-line
	evil-delete-char
	evil-end-of-line
	evil-force-normal-state
	evil-forward-char
	))

(setq mc/cmds-to-run-once
      '(
	evil-next-line
	evil-previous-line
	))
